AllCops:
  Include:
    - 'app/**/*'
    - 'test/**/*'

  Exclude:
    - 'app/assets/**/*'
    - 'app/views/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - '**/*.yml'
    - '**/Rakefile'
Documentation:
  Enabled: false
